const fs=require('fs'),path=require('path');
const src=fs.readFileSync(process.argv[2]||'core.js','utf8');const core=src.match(/\/\/<core>([\s\S]*?)\/\/<\/core>/)[1];
const names=[...core.matchAll(/(?:^|\n)(?:const|function)\s+([A-Za-z0-9_]+)/g)].map(m=>m[1]);
const api=new Function(core+'\nreturn {'+[...new Set(names)].join(',')+'}')();
let pass=0,fail=0;const t=(n,f)=>{try{f();pass++;console.log('PASS',n)}catch(e){fail++;console.log('FAIL',n,'-',e.message)}};
const eq=(a,b,m)=>{if(a!==b)throw new Error((m||'')+`\n expected ${JSON.stringify(b)}\n      got ${JSON.stringify(a)}`)};const ok=(c,m)=>{if(!c)throw new Error(m||'assert')};
const {pdfStripText,changedPatches,affFromPoints,applyAff,affUnrotated,pickPdfFont,stdFontName}=api;
const S=(x,y)=>({x,y});
t('real reportlab stream: blank one line, keep the rest',()=>{const c=fs.existsSync('/tmp/t1.content.txt')?fs.readFileSync('/tmp/t1.content.txt','latin1'):null;if(!c)return;
  const r=pdfStripText(c,[S(72,691.8898)]);eq(r.matched,1);ok(r.out.includes('() Tj')&&!r.out.includes('Total due')&&r.out.includes('Customer: Nikhil')&&r.out.includes('Line three, unchanged'))});
t('paragraph: only the targeted line goes (T* repositions)',()=>{const c='BT 1 0 0 1 72 651.8898 Tm /F3 12 Tf 14.4 TL (Line one) Tj T* (Line two) Tj T* (Line three) Tj T* ET';
  const r=pdfStripText(c,[S(72,637.4898)]);eq(r.matched,1);eq(r.out,'BT 1 0 0 1 72 651.8898 Tm /F3 12 Tf 14.4 TL (Line one) Tj T* () Tj T* (Line three) Tj T* ET')});
t('chained runs with no repositioning go together, next line is safe',()=>{const c='BT /F1 10 Tf 100 200 Td (Hello ) Tj (world) Tj 0 -12 Td (next) Tj ET';const r=pdfStripText(c,[S(100,200)]);eq(r.matched,2);eq(r.out,'BT /F1 10 Tf 100 200 Td () Tj () Tj 0 -12 Td (next) Tj ET')});
t('TJ arrays, hex strings and escaped parens',()=>{const c='BT 1 0 0 1 10 20 Tm [(A)-120(B\\)C)] TJ ET BT 1 0 0 1 10 40 Tm <00480065006C> Tj ET BT 1 0 0 1 10 60 Tm (keep \\(me\\)) Tj ET';
  const r=pdfStripText(c,[S(10,20),S(10,40)]);eq(r.matched,2);eq(r.out,'BT 1 0 0 1 10 20 Tm [] TJ ET BT 1 0 0 1 10 40 Tm <> Tj ET BT 1 0 0 1 10 60 Tm (keep \\(me\\)) Tj ET')});
t('cm scaling and q/Q are applied to the start point',()=>{const c='q 0.5 0 0 0.5 100 100 cm BT 1 0 0 1 40 60 Tm (scaled) Tj ET Q BT 1 0 0 1 40 60 Tm (plain) Tj ET';
  const r=pdfStripText(c,[S(120,130)]);eq(r.matched,1);ok(r.out.includes('() Tj')&&r.out.includes('(plain) Tj'))});
t('text rise, TD leading, quote operators',()=>{const c="BT 1 0 0 1 50 300 Tm 14 TL (one) Tj (two) ' (three) ' ET";const r=pdfStripText(c,[S(50,286),S(50,300)]);eq(r.matched,2,'first quote line and the run before it are matched, the third line is not');
  const r2=pdfStripText(c,[S(50,272)]);eq(r2.matched,1);eq(r2.out,"BT 1 0 0 1 50 300 Tm 14 TL (one) Tj (two) ' () ' ET")});
t('comments, inline images and dict operands do not confuse the tokenizer',()=>{const c='% (fake) Tj\nBI /W 2 /H 2 /BPC 8 /CS /G ID \x01(\x02) Tj\x03 EI\n/OC /MC0 BDC BT 1 0 0 1 5 5 Tm (real) Tj ET EMC /Span <</MCID 0>> BDC BT 1 0 0 1 9 9 Tm (other) Tj ET EMC';
  const r=pdfStripText(c,[S(5,5)]);eq(r.matched,1);ok(r.out.includes('(other) Tj')&&r.out.includes('() Tj')&&r.out.includes('(fake) Tj')&&r.out.includes('\x01(\x02) Tj\x03'))});
t('tolerance and no-match leave the stream untouched',()=>{const c='BT 1 0 0 1 72 100 Tm (x) Tj ET';eq(pdfStripText(c,[S(72.5,100.4)]).matched,1);const r=pdfStripText(c,[S(90,100)]);eq(r.matched,0);eq(r.out,c)});
t('changedPatches finds tight boxes, merges neighbours, reports area',()=>{const W=200,H=100,a=new Uint8ClampedArray(W*H*4).fill(200),b=new Uint8ClampedArray(a);
  for(let y=20;y<30;y++)for(let x=40;x<90;x++){const i=(y*W+x)*4;b[i]=10}for(let y=20;y<30;y++)for(let x=94;x<120;x++){const i=(y*W+x)*4;b[i]=10}for(let y=70;y<80;y++)for(let x=150;x<160;x++){const i=(y*W+x)*4;b[i+1]=0}
  const r=changedPatches(a,b,W,H);eq(r.boxes.length,2,JSON.stringify(r.boxes));const A=r.boxes.find(q=>q.y0<50);eq(A.x0,40);eq(A.x1,120);eq(A.y0,20);eq(A.y1,30);ok(r.frac>.01&&r.frac<.06,'frac '+r.frac);eq(changedPatches(a,a,W,H).boxes.length,0)});
t('affine maps canvas to PDF space (unrotated page, scale 1.8)',()=>{const sc=1.8,f=affFromPoints([0,842],[1/sc,842],[0,842-1/sc]);ok(affUnrotated(f));const p=applyAff(f,sc*72,(842-100)*sc);ok(Math.abs(p[0]-72)<1e-6&&Math.abs(p[1]-100)<1e-3,JSON.stringify(p))});
t('font picking: standard, bold, italic, web families',()=>{eq(pickPdfFont('Arial,Helvetica,sans-serif',700,false).name,'Helvetica-Bold');eq(pickPdfFont('Georgia,"Times New Roman",serif',400,true).name,'Times-Italic');
  eq(pickPdfFont('ui-monospace,"Courier New",monospace',400,false).name,'Courier');const w=pickPdfFont('"Roboto",sans-serif',500,false);eq(w.kind,'web');eq(w.id,'roboto');eq(pickPdfFont('system-ui,-apple-system,sans-serif',400,false).base,'Helvetica');eq(stdFontName('Courier',true,true),'Courier-BoldOblique')});
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
