"""Author / credits shown in the UI, exports, API and generated code headers."""
AUTHOR = {
    "name": "Nikhil Chary Sriramoju",
    "role": "Designer & Lead Developer — BTech CSE (Final Year)",
    "github": "https://github.com/Nikhil-creat",
    "linkedin": "https://in.linkedin.com/in/nikhil-chary-sriramoju-95041b38a",
    "email": "sriramojunikhil66@gmail.com",
    "mobile": "+91 6300556301",
}
PRODUCT = "Aether AI Screenshot Studio"
VERSION = "2.0.0"
TAGLINE = "Autonomous, private, self-healing screenshot intelligence."
HEADER = f"Generated by {PRODUCT} v{VERSION} — designed & built by {AUTHOR['name']} ({AUTHOR['github']})"
